import Head from "next/head";
import Button from "@mui/material/Button";
import { useSession, signIn, signOut } from "next-auth/react";
import { Avatar } from "@mui/material";

export default function Home() {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>holaa</h1>
        <Button variant="contained">Hello World</Button>

        {session ? (
          <div>
            Logeado como : {session.user?.email}
            <Avatar
              alt="Remy Sharp"
              src={session.user?.image ?? ""}
              sx={{ width: 56, height: 56 }}
            />
            <Button
              variant="contained"
              onClick={() => {
                signOut();
              }}
            >
              Disconnect
            </Button>
          </div>
        ) : (
          <div>
            nop no lo estas
            <Button
              variant="contained"
              onClick={() => {
                signIn();
              }}
            >
              SignIn
            </Button>
          </div>
        )}
      </main>
    </>
  );
}
